#!/usr/bin/env python3
"""Generate klik-pos.yaml for Swagger UI. Run: python3 scripts/generate_klik_pos_openapi.py (from app root)."""
from __future__ import annotations

import textwrap
from pathlib import Path

HEADER = textwrap.dedent(
    """\
    openapi: 3.0.3
    info:
      title: KLiK POS API
      version: "1.0.0"
      description: |
        API surface used by the KLiK POS React SPA and related Frappe/ERPNext integrations.

        Try it out — behavior on this page:
        - GET requests are sent to your real Frappe site (live data). Use Authorize with a Frappe API token: token api_key:api_secret (generate from User → API Access).
        - POST, PUT, DELETE, PATCH to /api/* are intercepted in the browser and return static mock JSON only. No documents are created, updated, or deleted. This is intentional for safe demos.

        Session isolation:
        Token auth uses the Authorization header only; it does not log you into the POS SPA or Desk. Opening /klik_pos or /login still requires normal login.

    servers:
      - url: /
        description: Same origin (current Frappe site)

    tags:
      - name: AuthAndSession
        description: Login helpers, CSRF, current user (Frappe + klik_pos)
      - name: POSSession
        description: POS open / opening / closing entry
      - name: POSProfileTax
        description: POS profile and tax categories
      - name: Payments
        description: Payment modes and shift payment data
      - name: CatalogPricing
        description: Items, stock, barcodes, pricing rules
      - name: ItemManagement
        description: Item CRUD helpers for the SPA item screens
      - name: Customers
        description: Customer search and maintenance
      - name: SalesInvoices
        description: Sales invoices, payments, returns
      - name: DashboardAnalytics
        description: Dashboard KPIs and drilldowns
      - name: Purchase
        description: Purchase invoices
      - name: Suppliers
        description: Suppliers
      - name: DateWiseInventory
        description: Date-wise inventory report API
      - name: Delivery
        description: Delivery personnel
      - name: Communications
        description: Email, WhatsApp, SMS
      - name: Outstanding
        description: Receive outstanding payments
      - name: Cache
        description: Backend cache utilities
      - name: FrappeClient
        description: Generic Frappe client / resource APIs used by the SPA

    components:
      securitySchemes:
        tokenAuth:
          type: apiKey
          in: header
          name: Authorization
          description: |
            Frappe token authentication. Value must be exactly:
            `token <api_key>:<api_secret>`
            (no brackets). Generate keys from the User document → API Access.

      schemas:
        FrappeStandardResponse:
          type: object
          description: Typical Frappe JSON response; shape varies by method.
          additionalProperties: true
        MockNotice:
          type: object
          required: [_mock, _message]
          properties:
            _mock:
              type: boolean
              example: true
            _message:
              type: string
              example: "Swagger UI demo — this response was not generated by the server."

    security:
      - tokenAuth: []
    """
)

MOCK_FOOTER = textwrap.dedent(
    """

        DEMO MODE (this page only): When you use Try it out / Execute for this operation on
        `/klik_pos/api-docs`, the browser returns a static mock response and does not call
        the real server. No data is mutated.
    """
)


def op_get(tag: str, summary: str, description: str, parameters: list | None = None):
    params = parameters or []
    if not params:
        params_section = "parameters: []"
    else:
        lines = []
        for p in params:
            loc = p.get("in", "query")
            lines.append(f"""    - name: {p["name"]}
      in: {loc}
      required: {str(p.get("required", False)).lower()}
      schema:
        type: {p.get("type", "string")}
      description: {p.get("desc", "")}""")
        params_section = "parameters:\n" + "\n".join(lines)
    return f"""get:
  tags:
    - {tag}
  summary: "{summary.replace('"', "'")}"
  description: |
    {textwrap.indent(description.strip(), "    ")}
  {params_section}
  responses:
    "200":
      description: Success (live response from Frappe when using Try it out on this page)
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/FrappeStandardResponse"
    "401":
      description: Unauthorized / invalid token
    "403":
      description: Forbidden
"""


def op_post_mock(tag: str, summary: str, description: str, request_example: dict | None = None):
    import json

    combined_desc = f"{description.strip()}\n\n{MOCK_FOOTER.strip()}"
    if request_example is not None:
        ex = json.dumps(request_example, indent=2)
        body = f"""  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          additionalProperties: true
        example:
{textwrap.indent(ex, "          ")}
"""
    else:
        body = """  requestBody:
    content:
      application/json:
        schema:
          type: object
          additionalProperties: true
"""
    desc_block = textwrap.indent(combined_desc, "    ")
    return f"""post:
  tags:
    - {tag}
  summary: "{summary.replace('"', "'")}"
  description: |
{desc_block}
{body}  responses:
    "200":
      description: Mock response only (browser interceptor on api-docs page)
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/FrappeStandardResponse"
          example:
            _mock: true
            message:
              success: true
              note: "Static demo response"
"""


def path_block(path: str, *operations_yaml: str) -> str:
    ops = "\n".join(o.strip() for o in operations_yaml)
    return f"  {path}:\n{textwrap.indent(ops, '    ')}\n"


# (tag, path_suffix, summary, desc, params_for_get) — path_suffix is after /api/method/
GET_SPECS: list[tuple] = [
    (
        "AuthAndSession",
        "frappe.auth.get_logged_user",
        "Get logged-in user",
        "Returns the current user id if session is valid; with token auth returns the API user.",
        [],
    ),
    (
        "AuthAndSession",
        "klik_pos.api.user.get_spa_csrf_token",
        "Get CSRF token for SPA POSTs",
        "Used by the React SPA for `X-Frappe-CSRF-Token` when using cookie session (not used with pure token auth).",
        [],
    ),
    (
        "AuthAndSession",
        "klik_pos.api.user.get_user_roles",
        "Get roles for current user",
        "Returns roles and admin flags.",
        [],
    ),
    (
        "AuthAndSession",
        "klik_pos.api.user.get_current_user_info",
        "Get current user info for POS",
        "User, roles, POS profile context.",
        [],
    ),
    (
        "POSSession",
        "klik_pos.api.pos_entry.open_pos",
        "Open POS session",
        "POS session bootstrap used by the SPA.",
        [],
    ),
    (
        "POSProfileTax",
        "klik_pos.api.pos_profile.get_pos_profiles_for_user",
        "POS profiles for user",
        "List POS profiles available to the logged-in user.",
        [],
    ),
    (
        "POSProfileTax",
        "klik_pos.api.pos_profile.get_pos_details",
        "POS profile details",
        "Details for templates, WhatsApp, etc.",
        [{"name": "pos_profile", "type": "string", "desc": "POS Profile name", "required": False}],
    ),
    (
        "POSProfileTax",
        "klik_pos.api.tax.get_sales_tax_categories",
        "Sales tax categories",
        "Tax categories for the cart.",
        [],
    ),
    (
        "Payments",
        "klik_pos.api.payment.get_payment_modes",
        "Payment modes for POS",
        "Modes of payment for the register.",
        [{"name": "pos_profile", "type": "string", "desc": "POS Profile", "required": False}],
    ),
    (
        "Payments",
        "klik_pos.api.payment.get_all_mode_of_payment",
        "All modes of payment",
        "Full list of Mode of Payment.",
        [],
    ),
    (
        "Payments",
        "klik_pos.api.payment.get_opening_entry_payment_summary",
        "Opening entry payment summary",
        "Summary for current opening entry.",
        [],
    ),
    (
        "Payments",
        "klik_pos.api.payment.get_payment_transactions",
        "Payment transactions for closing",
        "Transactions list with optional cashier filter.",
        [{"name": "cashier_filter", "type": "string", "desc": "Optional cashier filter", "required": False}],
    ),
    (
        "CatalogPricing",
        "klik_pos.api.item.get_items_with_balance_and_price",
        "Items with stock and price",
        "Main catalog feed for the POS grid.",
        [
            {"name": "warehouse", "type": "string", "desc": "Warehouse", "required": False},
            {"name": "price_list", "type": "string", "desc": "Price list", "required": False},
            {"name": "item_group", "type": "string", "desc": "Item group filter", "required": False},
        ],
    ),
    (
        "CatalogPricing",
        "klik_pos.api.item.get_item_by_identifier",
        "Get item by barcode or code",
        "Lookup for scanning/search.",
        [{"name": "code", "type": "string", "desc": "Item code or barcode", "required": True}],
    ),
    (
        "CatalogPricing",
        "klik_pos.api.item.get_item_by_barcode",
        "Get item by barcode",
        "Barcode lookup.",
        [{"name": "barcode", "type": "string", "desc": "Barcode", "required": True}],
    ),
    (
        "CatalogPricing",
        "klik_pos.api.item.get_item_groups_for_pos",
        "Item groups for POS",
        "Category list for filters.",
        [],
    ),
    (
        "CatalogPricing",
        "klik_pos.api.item.get_items_stock_batch",
        "Batch stock for items",
        "Comma-separated item_codes.",
        [{"name": "item_codes", "type": "string", "desc": "Comma-separated item codes", "required": True}],
    ),
    (
        "CatalogPricing",
        "klik_pos.api.item.get_batch_nos_with_qty",
        "Batch numbers with qty",
        "For batch-tracked items.",
        [{"name": "item_code", "type": "string", "desc": "Item code", "required": True}],
    ),
    (
        "CatalogPricing",
        "klik_pos.api.item.get_item_uoms_and_prices",
        "UOMs and prices for item",
        "Cart line UOM/price.",
        [
            {"name": "item_code", "type": "string", "desc": "Item code", "required": True},
            {"name": "customer", "type": "string", "desc": "Customer", "required": False},
        ],
    ),
    (
        "CatalogPricing",
        "klik_pos.api.item.get_item_price_for_customer",
        "Item price for customer",
        "Customer-specific price.",
        [
            {"name": "item_code", "type": "string", "desc": "Item code", "required": True},
            {"name": "customer", "type": "string", "desc": "Customer", "required": False},
            {"name": "uom", "type": "string", "desc": "UOM", "required": False},
        ],
    ),
    (
        "CatalogPricing",
        "klik_pos.api.item.apply_pricing_rules_to_cart",
        "Apply pricing rules (GET with cart_items JSON)",
        "Pass cart_items as URL-encoded JSON string (as SPA does).",
        [
            {"name": "cart_items", "type": "string", "desc": "JSON string of cart lines", "required": True},
            {"name": "customer", "type": "string", "desc": "Customer", "required": False},
        ],
    ),
    (
        "CatalogPricing",
        "klik_pos.api.item.get_serial_nos_for_item",
        "Serial numbers for item",
        "Serial-tracked stock.",
        [{"name": "item_code", "type": "string", "desc": "Item code", "required": True}],
    ),
    (
        "CatalogPricing",
        "klik_pos.api.item.get_stock_updates",
        "Stock updates since last sync",
        "Polling endpoint for background sync.",
        [],
    ),
    (
        "ItemManagement",
        "klik_pos.api.item.get_item_detail_for_spa",
        "Item detail for SPA",
        "Full item screen payload.",
        [{"name": "item_code", "type": "string", "desc": "Item code", "required": True}],
    ),
    (
        "ItemManagement",
        "klik_pos.api.item.get_item_stock",
        "Item stock",
        "Stock for one item.",
        [{"name": "item_code", "type": "string", "desc": "Item code", "required": True}],
    ),
    (
        "ItemManagement",
        "klik_pos.api.item.get_item_prices",
        "Item prices",
        "Buying/selling price rows.",
        [{"name": "item_code", "type": "string", "desc": "Item code", "required": True}],
    ),
    (
        "ItemManagement",
        "klik_pos.api.item.get_item_batch_stock_details",
        "Batch stock details",
        "Batch breakdown for item.",
        [{"name": "item_code", "type": "string", "desc": "Item code", "required": True}],
    ),
    (
        "ItemManagement",
        "klik_pos.api.item.check_barcode_exists",
        "Check barcode exists",
        "Before creating items.",
        [{"name": "barcode", "type": "string", "desc": "Barcode", "required": True}],
    ),
    (
        "ItemManagement",
        "klik_pos.api.item.get_inactive_items",
        "Inactive items list",
        "Paginated inactive items.",
        [
            {"name": "start", "type": "string", "desc": "Start offset", "required": False},
            {"name": "limit", "type": "string", "desc": "Page size", "required": False},
        ],
    ),
    (
        "ItemManagement",
        "klik_pos.api.item.get_items_for_export",
        "Items export payload",
        "Data for CSV/export.",
        [],
    ),
    (
        "ItemManagement",
        "klik_pos.api.item.get_current_stock",
        "Current stock",
        "Qty by warehouse/batch.",
        [
            {"name": "item_code", "type": "string", "desc": "Item code", "required": True},
            {"name": "warehouse", "type": "string", "desc": "Warehouse", "required": True},
            {"name": "batch_no", "type": "string", "desc": "Batch", "required": False},
        ],
    ),
    (
        "ItemManagement",
        "klik_pos.api.item.get_item_purchase_history",
        "Purchase history for item",
        "Recent purchase lines.",
        [
            {"name": "item_code", "type": "string", "desc": "Item code", "required": True},
            {"name": "limit", "type": "string", "desc": "Limit", "required": False},
        ],
    ),
    (
        "ItemManagement",
        "klik_pos.api.item.get_last_bought_supplier",
        "Last bought supplier",
        "For purchase flow.",
        [{"name": "item_code", "type": "string", "desc": "Item code", "required": True}],
    ),
    (
        "ItemManagement",
        "klik_pos.api.item.get_item_buying_price_history",
        "Buying price history",
        "Historical buy rates.",
        [
            {"name": "item_code", "type": "string", "desc": "Item code", "required": True},
            {"name": "limit", "type": "string", "desc": "Limit", "required": False},
        ],
    ),
    (
        "Customers",
        "klik_pos.api.customer.get_customers",
        "Search customers",
        "Customer typeahead.",
        [
            {"name": "search", "type": "string", "desc": "Search text", "required": False},
            {"name": "limit", "type": "string", "desc": "Limit", "required": False},
            {"name": "start", "type": "string", "desc": "Start", "required": False},
        ],
    ),
    (
        "Customers",
        "klik_pos.api.customer.get_customer_info",
        "Customer info",
        "Single customer card.",
        [{"name": "customer_name", "type": "string", "desc": "Customer id/name", "required": True}],
    ),
    (
        "Customers",
        "klik_pos.api.customer.get_customer_addresses",
        "Customer addresses",
        "Shipping/billing addresses.",
        [{"name": "customer", "type": "string", "desc": "Customer", "required": True}],
    ),
    (
        "Customers",
        "klik_pos.api.customer.get_customer_groups",
        "Customer groups",
        "Dropdown.",
        [],
    ),
    (
        "Customers",
        "klik_pos.api.customer.get_territories",
        "Territories",
        "Dropdown.",
        [],
    ),
    (
        "Customers",
        "klik_pos.api.customer.get_currency_exchange_rate",
        "Currency exchange rate",
        "FX rate.",
        [
            {"name": "from_currency", "type": "string", "desc": "From", "required": True},
            {"name": "to_currency", "type": "string", "desc": "To", "required": True},
            {"name": "transaction_date", "type": "string", "desc": "Date", "required": False},
        ],
    ),
    (
        "Customers",
        "klik_pos.api.customer.get_customer_statistics",
        "Customer statistics",
        "Stats for customer.",
        [{"name": "customer_id", "type": "string", "desc": "Customer", "required": True}],
    ),
    (
        "Customers",
        "klik_pos.api.customer.get_global_totals",
        "Global totals",
        "Aggregate customer metrics.",
        [],
    ),
    (
        "Customers",
        "klik_pos.api.customer.check_customer_permission",
        "Check customer permission",
        "Permission guard.",
        [{"name": "customer_name", "type": "string", "desc": "Customer", "required": True}],
    ),
    (
        "SalesInvoices",
        "klik_pos.api.sales_invoice.get_sales_invoices",
        "List sales invoices",
        "Paginated history.",
        [
            {"name": "limit", "type": "string", "desc": "Limit", "required": False},
            {"name": "start", "type": "string", "desc": "Start", "required": False},
            {"name": "search", "type": "string", "desc": "Search", "required": False},
        ],
    ),
    (
        "SalesInvoices",
        "klik_pos.api.sales_invoice.get_invoice_details",
        "Invoice details",
        "Single invoice for view/print.",
        [{"name": "invoice_id", "type": "string", "desc": "Invoice name", "required": True}],
    ),
    (
        "SalesInvoices",
        "klik_pos.api.sales_invoice.get_invoice_payment_status",
        "Invoice payment status",
        "Paid/outstanding breakdown.",
        [{"name": "invoice_name", "type": "string", "desc": "Invoice", "required": True}],
    ),
    (
        "SalesInvoices",
        "klik_pos.api.sales_invoice.returned_qty",
        "Returned qty for line",
        "Return limits.",
        [
            {"name": "customer", "type": "string", "desc": "Customer", "required": True},
            {"name": "sales_invoice", "type": "string", "desc": "Invoice", "required": True},
            {"name": "item", "type": "string", "desc": "Item code", "required": True},
        ],
    ),
    (
        "SalesInvoices",
        "klik_pos.api.sales_invoice.get_customer_invoices_for_return",
        "Invoices available for return",
        "Pick source invoices.",
        [
            {"name": "customer", "type": "string", "desc": "Customer", "required": True},
            {"name": "start_date", "type": "string", "desc": "Start date", "required": False},
            {"name": "end_date", "type": "string", "desc": "End date", "required": False},
        ],
    ),
    (
        "SalesInvoices",
        "klik_pos.api.sales_invoice.get_valid_sales_invoices",
        "Valid sales invoices (link search)",
        "Frappe link field search.",
        [
            {"name": "doctype", "type": "string", "desc": "Doctype", "required": True},
            {"name": "txt", "type": "string", "desc": "Search text", "required": False},
            {"name": "searchfield", "type": "string", "desc": "Field", "required": False},
            {"name": "start", "type": "string", "desc": "Start", "required": False},
            {"name": "page_len", "type": "string", "desc": "Page length", "required": False},
        ],
    ),
    (
        "DashboardAnalytics",
        "klik_pos.api.sales_invoice.get_dashboard_analytics",
        "Dashboard analytics",
        "KPIs and chart data.",
        [
            {"name": "time_range", "type": "string", "desc": "Time range key", "required": False},
            {"name": "cashier_name", "type": "string", "desc": "Cashier filter", "required": False},
            {"name": "payment_method", "type": "string", "desc": "Payment filter", "required": False},
        ],
    ),
    (
        "DashboardAnalytics",
        "klik_pos.api.sales_invoice.get_dashboard_product_invoice_drilldown",
        "Product invoice drilldown",
        "Line-level drilldown for dashboard.",
        [
            {"name": "item_code", "type": "string", "desc": "Item code", "required": False},
            {"name": "time_range", "type": "string", "desc": "Time range", "required": False},
        ],
    ),
    (
        "Purchase",
        "klik_pos.api.purchase_invoice.get_purchase_invoices",
        "List purchase invoices",
        "Purchase history.",
        [
            {"name": "limit", "type": "string", "desc": "Limit", "required": False},
            {"name": "start", "type": "string", "desc": "Start", "required": False},
            {"name": "search", "type": "string", "desc": "Search", "required": False},
        ],
    ),
    (
        "Purchase",
        "klik_pos.api.purchase_invoice.get_purchase_invoice_details",
        "Purchase invoice details",
        "Single PI.",
        [{"name": "invoice_id", "type": "string", "desc": "PI name", "required": True}],
    ),
    (
        "Suppliers",
        "klik_pos.api.supplier.get_suppliers",
        "Search suppliers",
        "Supplier typeahead.",
        [
            {"name": "search", "type": "string", "desc": "Search", "required": False},
            {"name": "limit", "type": "string", "desc": "Limit", "required": False},
        ],
    ),
    (
        "Suppliers",
        "klik_pos.api.supplier.get_supplier_info",
        "Supplier info",
        "Detail card.",
        [{"name": "supplier_name", "type": "string", "desc": "Supplier", "required": True}],
    ),
    (
        "Suppliers",
        "klik_pos.api.supplier.get_supplier_groups",
        "Supplier groups",
        "Dropdown.",
        [],
    ),
    (
        "Suppliers",
        "klik_pos.api.supplier.get_supplier_statistics",
        "Supplier statistics",
        "Stats.",
        [{"name": "supplier_id", "type": "string", "desc": "Supplier", "required": True}],
    ),
    (
        "DateWiseInventory",
        "klik_pos.api.date_wise_inventory.get_bs_defaults",
        "BS calendar defaults",
        "Nepali calendar defaults if used.",
        [],
    ),
    (
        "DateWiseInventory",
        "klik_pos.api.date_wise_inventory.bs_to_ad",
        "BS to AD",
        "Convert single BS date.",
        [
            {"name": "bs_year", "type": "string", "desc": "Year", "required": True},
            {"name": "bs_month", "type": "string", "desc": "Month", "required": True},
            {"name": "bs_day", "type": "string", "desc": "Day", "required": True},
        ],
    ),
    (
        "DateWiseInventory",
        "klik_pos.api.date_wise_inventory.bs_range_to_ad",
        "BS range to AD",
        "Convert BS range.",
        [
            {"name": "from_year", "type": "string", "desc": "From year", "required": True},
            {"name": "from_month", "type": "string", "desc": "From month", "required": True},
            {"name": "from_day", "type": "string", "desc": "From day", "required": True},
            {"name": "to_year", "type": "string", "desc": "To year", "required": True},
            {"name": "to_month", "type": "string", "desc": "To month", "required": True},
            {"name": "to_day", "type": "string", "desc": "To day", "required": True},
        ],
    ),
    (
        "DateWiseInventory",
        "klik_pos.api.date_wise_inventory.get_filter_options",
        "Report filter options",
        "Metadata for filters.",
        [],
    ),
    (
        "DateWiseInventory",
        "klik_pos.api.date_wise_inventory.get_items_search",
        "Item search for report",
        "Search items in report context.",
        [
            {"name": "search", "type": "string", "desc": "Search", "required": False},
            {"name": "limit", "type": "string", "desc": "Limit", "required": False},
        ],
    ),
    (
        "Delivery",
        "klik_pos.api.delivery_personnel.get_delivery_personnel_list",
        "Delivery personnel list",
        "For delivery assignment.",
        [],
    ),
    (
        "Communications",
        "klik_pos.api.email.get_email_templates",
        "Email templates",
        "List templates.",
        [],
    ),
    (
        "Communications",
        "klik_pos.api.email.get_email_template",
        "Get email template",
        "Single template.",
        [{"name": "template_name", "type": "string", "desc": "Template name", "required": True}],
    ),
    (
        "Communications",
        "klik_pos.api.whatsapp.get_whatsapp_templates",
        "WhatsApp templates",
        "List WhatsApp templates.",
        [],
    ),
    (
        "Communications",
        "klik_pos.api.whatsapp.get_whatsapp_template",
        "Get WhatsApp template",
        "Single template.",
        [{"name": "template_name", "type": "string", "desc": "Name", "required": True}],
    ),
    (
        "Communications",
        "klik_pos.api.sms.get_sms_settings",
        "SMS settings",
        "Settings introspection.",
        [],
    ),
    (
        "Cache",
        "klik_pos.api.cache.clear_backend_cache",
        "Clear backend cache",
        "Clears POS-related server cache. Whitelisted GET typically works; SPA may call POST.",
        [],
    ),
]

# Mutating POST operations (mocked in browser on api-docs page)
POST_SPECS: list[tuple] = [
    ("AuthAndSession", "/api/method/login", "Login (mock on this page)", "Frappe login with usr/pwd.", {"usr": "demo@example.com", "pwd": "***"}),
    ("AuthAndSession", "/api/method/logout", "Logout (mock on this page)", "End session.", {}),
    ("POSSession", "/api/method/klik_pos.api.pos_entry.create_opening_entry", "Create opening entry", "Start of day float.", {"pos_profile": "Store"}),
    ("POSSession", "/api/method/klik_pos.api.pos_entry.create_closing_entry", "Create closing entry", "End of shift.", {}),
    ("ItemManagement", "/api/method/klik_pos.api.item.create_item_with_barcode", "Create item with barcode", "New item master.", {"item_name": "Demo Item", "barcode": "1234567890123"}),
    ("ItemManagement", "/api/method/klik_pos.api.item.create_opening_stock", "Create opening stock", "Opening qty.", {"item_code": "ITEM-001", "qty": 10}),
    ("ItemManagement", "/api/method/klik_pos.api.item.update_item_prices", "Update item prices", "Item Price rows.", {"item_code": "ITEM-001", "selling_price": 100, "buying_price": 80}),
    ("ItemManagement", "/api/method/klik_pos.api.item.update_item_prices_with_validity", "Update prices with validity", "Price with validity window.", {"item_code": "ITEM-001"}),
    ("ItemManagement", "/api/method/klik_pos.api.item.update_item_barcode", "Update item barcode", "Barcode child table.", {"item_code": "ITEM-001", "barcode": "5901234123457"}),
    ("ItemManagement", "/api/method/klik_pos.api.item.update_item_image", "Update item image", "Base64 image data.", {"item_code": "ITEM-001", "image_data": "<base64>"}),
    ("ItemManagement", "/api/method/klik_pos.api.item.update_opening_stock", "Update opening stock", "Stock adjustment from SPA.", {"item_code": "ITEM-001", "qty": 5}),
    ("ItemManagement", "/api/method/klik_pos.api.item.set_item_disabled", "Enable/disable item", "disabled 0 or 1.", {"item_code": "ITEM-001", "disabled": 0}),
    ("FrappeClient", "/api/method/frappe.client.set_value", "Set field values on document", "Partial doc update.", {"doctype": "Item", "name": "ITEM-001", "fieldname": {"description": "Updated"}}),
    ("FrappeClient", "/api/method/frappe.client.get_list", "Generic get_list", "List any doctype.", {"doctype": "UOM", "fields": ["name"], "limit_page_length": 20}),
    ("Customers", "/api/method/klik_pos.api.customer.create_or_update_customer", "Create or update customer", "Quick customer.", {"customer_name": "Walk-in Customer"}),
    ("Customers", "/api/method/klik_pos.api.customer.update_customer", "Update customer", "By id.", {"customer_id": "CUST-001", "customer_data": {}}),
    ("SalesInvoices", "/api/method/klik_pos.api.sales_invoice.create_draft_invoice", "Create draft invoice", "Save cart as draft.", {"items": []}),
    ("SalesInvoices", "/api/method/klik_pos.api.sales_invoice.create_and_submit_invoice", "Create and submit invoice", "Finalize sale.", {"items": [], "customer": "Customer"}),
    ("SalesInvoices", "/api/method/klik_pos.api.sales_invoice.submit_draft_invoice", "Submit draft invoice", "Submit existing draft.", {"invoice_id": "SINV-00001"}),
    ("SalesInvoices", "/api/method/klik_pos.api.sales_invoice.delete_draft_invoice", "Delete draft invoice", "Remove draft.", {"invoice_id": "SINV-00001"}),
    ("SalesInvoices", "/api/method/klik_pos.api.sales_invoice.return_sales_invoice", "Return sales invoice", "Full return.", {"invoice_name": "SINV-00001"}),
    ("SalesInvoices", "/api/method/klik_pos.api.sales_invoice.pay_unpaid_invoice", "Pay unpaid invoice", "Payment against SI.", {"invoice_name": "SINV-00001", "mode_of_payment": "Cash", "amount": 100}),
    ("SalesInvoices", "/api/method/klik_pos.api.sales_invoice.update_invoice_outstanding", "Refresh outstanding", "Recalculate outstanding.", {"invoice_name": "SINV-00001"}),
    ("SalesInvoices", "/api/method/klik_pos.api.sales_invoice.create_partial_return", "Partial return", "Line-level return.", {"return_data": {}}),
    ("SalesInvoices", "/api/method/klik_pos.api.sales_invoice.create_multi_invoice_return", "Multi-invoice return", "Complex return.", {"return_data": {}}),
    ("Purchase", "/api/method/klik_pos.api.purchase_invoice.create_purchase_invoice", "Create purchase invoice", "Supplier purchase.", {"supplier": "Supplier", "items": []}),
    ("Purchase", "/api/method/klik_pos.api.purchase_invoice.pay_purchase_invoice", "Pay purchase invoice", "Pay PI.", {"invoice_name": "PINV-00001", "mode_of_payment": "Cash"}),
    ("Purchase", "/api/method/klik_pos.api.purchase_invoice.return_purchase_invoice", "Return purchase invoice", "Return PI.", {"invoice_name": "PINV-00001"}),
    ("Purchase", "/api/method/klik_pos.api.purchase_invoice.delete_draft_purchase_invoice", "Delete draft PI", "Remove draft PI.", {"invoice_id": "PINV-00001"}),
    ("Suppliers", "/api/method/klik_pos.api.supplier.create_supplier", "Create supplier", "New supplier.", {"supplier_data": {"supplier_name": "New Supplier"}}),
    ("Suppliers", "/api/method/klik_pos.api.supplier.update_supplier", "Update supplier", "Update by id.", {"supplier_id": "SUP-001", "supplier_data": {}}),
    ("DateWiseInventory", "/api/method/klik_pos.api.date_wise_inventory.get_data", "Date-wise inventory data", "Usually POST with filters JSON — mocked here.", {"filters": {}, "page": 1}),
    ("DateWiseInventory", "/api/method/klik_pos.api.date_wise_inventory.export_pdf", "Export inventory PDF", "PDF export.", {"filters": {}}),
    ("Outstanding", "/api/method/klik_pos.api.receive_outstanding.receive_outstanding_prepare", "Prepare receive outstanding", "UI prep.", {"customer": "Customer"}),
    ("Outstanding", "/api/method/klik_pos.api.receive_outstanding.receive_outstanding_submit", "Submit receive outstanding", "Allocate payments.", {"customer": "Customer", "payments": []}),
    ("Communications", "/api/method/klik_pos.api.email.send_invoice_email", "Send invoice email", "Email delivery.", {"invoice_name": "SINV-00001"}),
    ("Communications", "/api/method/klik_pos.api.whatsapp.deliver_invoice_via_whatsapp", "Deliver invoice via WhatsApp", "WhatsApp with media.", {}),
    ("Communications", "/api/method/klik_pos.api.whatsapp.send_invoice_whatsapp", "Send invoice WhatsApp", "Alternate path.", {}),
    ("Communications", "/api/method/klik_pos.api.whatsapp.send_template_whatsapp", "Send WhatsApp template", "Template message.", {}),
    ("Communications", "/api/method/klik_pos.api.sms.send_invoice_sms", "Send invoice SMS", "SMS invoice.", {}),
    ("Communications", "/api/method/klik_pos.api.sms.send_sms_message", "Send SMS message", "Generic SMS.", {}),
    ("FrappeClient", "/api/method/upload_file", "Upload file", "Attach file (e.g. PI attachment).", {"is_private": 0, "folder": "Home"}),
    ("Communications", "/api/method/klik_pos.api.whatsap.webhook.webhook", "WhatsApp webhook (mock)", "Meta/cloud webhook callback.", {}),
]


def main():
    app_dir = Path(__file__).resolve().parent.parent
    out = app_dir / "klik_pos" / "public" / "openapi" / "klik-pos.yaml"
    parts = [HEADER]

    paths: dict[str, list[str]] = {}

    for tag, suffix, summary, desc, params in GET_SPECS:
        p = f"/api/method/{suffix}"
        yaml_op = op_get(tag, summary, desc, params)
        paths.setdefault(p, []).append(yaml_op)

    for tag, path, summary, desc, example in POST_SPECS:
        yaml_op = op_post_mock(tag, summary, desc, example)
        paths.setdefault(path, []).append(yaml_op)

    paths["/api/resource/User/{user_name}"] = [
        """get:
  tags:
    - AuthAndSession
  summary: Get User document (REST)
  description: |
    Standard Frappe REST document read. Returns `data` with User fields.
  parameters:
    - name: user_name
      in: path
      required: true
      schema:
        type: string
      description: User id (email)
  responses:
    "200":
      description: Success
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/FrappeStandardResponse"
    "401":
      description: Unauthorized
"""
    ]

    buf = []
    buf.append("paths:\n")
    for path_key in sorted(paths.keys()):
        buf.append(path_block(path_key, *paths[path_key]))

    text = "".join(parts) + "\n" + "".join(buf)
    out.write_text(text, encoding="utf-8")
    print(f"Wrote {out} ({len(text)} bytes)")


if __name__ == "__main__":
    main()
